name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - deploy-github-pages

# Permisos explícitos para evitar problemas de Git
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"

      - run: flutter --version
      - run: dart pub cache clean
      - run: flutter pub get
      - run: flutter build web --release

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
